version: '2'
services:
  nlp-slack-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
    environment:
      - REDIS_HOST=redis
    links:
      - redis
  redis:
    image: "redis:alpine"

